# Generated by Django 4.2.7 on 2025-04-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_instrument_instrumenttype_delete_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Pressure Instruments', 'Pressure Instruments'), ('Temperature Instruments', 'Temperature Instruments'), ('Test Instruments', 'Test Instruments')], max_length=100, unique=True),
        ),
    ]
