# Generated by Django 4.2.7 on 2025-04-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumenttype',
            name='name',
            field=models.CharField(choices=[('Pressure Gauges', 'Pressure Gauges'), ('Digital Gauges', 'Digital Gauges'), ('High-Purity', 'High-Purity'), ('Test Gauges', 'Test Gauges'), ('Differential Gauges', 'Differential Gauges'), ('Pressure Switches', 'Pressure Switches'), ('Pressure Sensors', 'Pressure Sensors'), ('Diaphragm Seals - Isolators', 'Diaphragm Seals - Isolators'), ('Threaded Seals', 'Threaded Seals'), ('Isolation Rings', 'Isolation Rings'), ('Flanged Seals', 'Flanged Seals'), ('In-Line', 'In-Line'), ('Accessories', 'Accessories'), ('Thermometers', 'Thermometers'), ('Bimetals Thermometers', 'Bimetals Thermometers'), ('Gas Actuated Thermometers', 'Gas Actuated Thermometers'), ('Thermowells', 'Thermowells'), ('Test Gauges', 'Test Gauges')], max_length=100),
        ),
    ]
