# Generated by Django 4.2.7 on 2025-04-22 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_configurablefield_parent_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurablefield',
            name='trigger_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='api.instrument')),
            ],
        ),
    ]
