# Generated by Django 4.2.7 on 2025-04-23 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_configurablefield_trigger_value_addon'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOnType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='addon',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='addon',
            name='label',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='addon',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='api.addontype'),
            preserve_default=False,
        ),
    ]
