# Generated by Django 4.2.7 on 2025-04-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_addontype_alter_addon_code_alter_addon_label_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addon',
            old_name='type',
            new_name='addon_type',
        ),
        migrations.RemoveField(
            model_name='addon',
            name='instrument',
        ),
        migrations.AddField(
            model_name='addontype',
            name='instruments',
            field=models.ManyToManyField(related_name='addon_types', to='api.instrument'),
        ),
    ]
