# Generated by Django 4.2.7 on 2025-05-06 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_quotation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quotation',
        ),
    ]
