# Generated by Django 4.2.7 on 2025-05-06 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_quotation_quotationinstrument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationinstrument',
            name='addons',
        ),
        migrations.RemoveField(
            model_name='quotationinstrument',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='quotationinstrument',
            name='quotation',
        ),
        migrations.RemoveField(
            model_name='quotationinstrument',
            name='selections',
        ),
        migrations.DeleteModel(
            name='Quotation',
        ),
        migrations.DeleteModel(
            name='QuotationInstrument',
        ),
    ]
