# Generated by Django 4.2.7 on 2025-05-06 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_quotation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quotation',
        ),
    ]
