# Generated by Django 4.2.7 on 2025-05-07 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_submittedconfiguration_quotation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submittedconfiguration',
            name='instrument',
        ),
        migrations.DeleteModel(
            name='Quotation',
        ),
        migrations.DeleteModel(
            name='SubmittedConfiguration',
        ),
    ]
