# Generated by Django 4.2.7 on 2025-05-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_quotation_quotationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
