# Generated by Django 4.2.7 on 2025-05-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_quotation_remarks_quotation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
