# Generated by Django 4.2.7 on 2025-05-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_quotation_rejected_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='project_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
