# Generated by Django 4.2.7 on 2025-05-17 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_quotation_project_name_alter_quotation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='project_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='QuotationItemSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fieldoption')),
                ('quotation_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='api.quotationitem')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationItemAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.addon')),
                ('quotation_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='api.quotationitem')),
            ],
        ),
    ]
