# Generated by Django 4.2.7 on 2025-06-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_addon_price_alter_fieldoption_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('submitted', 'Submitted')], default='pending', max_length=20),
        ),
    ]
