# Generated by Django 4.2.7 on 2025-06-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_quotation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='submitted_to_sales_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
