# Generated by Django 4.2.7 on 2025-06-17 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0030_quotation_submitted_to_sales_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='submitted_to_sales_at',
            new_name='emailed_at',
        ),
        migrations.AddField(
            model_name='quotation',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_quotations', to=settings.AUTH_USER_MODEL),
        ),
    ]
