# Generated by Django 4.2.7 on 2025-06-24 13:21

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_rename_submitted_to_sales_at_quotation_emailed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='instrument_images/%Y/%m/%d/'),
        ),
    ]
