# Generated by Django 4.2.7 on 2025-06-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_assistance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='sender_type',
            field=models.CharField(choices=[('client', 'Client'), ('agent', 'Agent'), ('system', 'System')], max_length=10),
        ),
    ]
