# Generated by Django 4.2.7 on 2025-06-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatmessage_file_data_chatmessage_file_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='file_data',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/%Y/%m/%d/'),
        ),
    ]
